### ISSUE TITLE
Select an activity on the map to view details

### ISSUE THREAD

**Issue by lijiayi0921** [ebrensi/heatflask#118]
It is a pleasure to view all the paths in which I was running, alone or with friends.

For me it is a way better experience than the paid "heatmap" of Strava.

Sometimes I find a path and ask myself "oh why did I pass here?". I think it would be nice to be possible to pick one path and redirect to the Strava page.

Developper myself (but newbie in web dev) I suppose it may require quite some re-factoring, based on how the data is structured. Hope you may have time to see this issue, and include it in the new data structure of your front-end refactoring.

Again, thanks for your work and for creating this amazing website !

**Comment by ebrensi** [comment]
Do you mean like this? ![screenshot_1606509068](https://user-images.githubusercontent.com/10375770/100482928-0f5a8c80-30ad-11eb-8b25-5d16a1bd0791.png)

It already is a feature.  If you graphically select one activity using `ctrl-mousedrag` with keyboard or the selection button (upper-right side), there should be a pop-up dialog box with the activity info and a Strava link.

Also, the corresponding entry will be selected in the activity table and you can click on the Strava link there.

If you have an idea about how the UX should look in order to make it easier, let me know.
